#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: 750e50d
#
Name     : draco
Version  : 1.5.6
Release  : 2
URL      : https://github.com/google/draco/archive/1.5.6/draco-1.5.6.tar.gz
Source0  : https://github.com/google/draco/archive/1.5.6/draco-1.5.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 Unlicense
Requires: draco-bin = %{version}-%{release}
Requires: draco-data = %{version}-%{release}
Requires: draco-lib = %{version}-%{release}
Requires: draco-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center">
<img width="350px" src="docs/artwork/draco3d-vert.svg" />
</p>

%package bin
Summary: bin components for the draco package.
Group: Binaries
Requires: draco-data = %{version}-%{release}
Requires: draco-license = %{version}-%{release}

%description bin
bin components for the draco package.


%package data
Summary: data components for the draco package.
Group: Data

%description data
data components for the draco package.


%package dev
Summary: dev components for the draco package.
Group: Development
Requires: draco-lib = %{version}-%{release}
Requires: draco-bin = %{version}-%{release}
Requires: draco-data = %{version}-%{release}
Provides: draco-devel = %{version}-%{release}
Requires: draco = %{version}-%{release}

%description dev
dev components for the draco package.


%package lib
Summary: lib components for the draco package.
Group: Libraries
Requires: draco-data = %{version}-%{release}
Requires: draco-license = %{version}-%{release}

%description lib
lib components for the draco package.


%package license
Summary: license components for the draco package.
Group: Default

%description license
license components for the draco package.


%prep
%setup -q -n draco-1.5.6
cd %{_builddir}/draco-1.5.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707075079
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707075079
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/draco
cp %{_builddir}/draco-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/draco/623115fff0087fad82d8c7a34b67dc8de932cf61 || :
cp %{_builddir}/draco-%{version}/docs/assets/css/pygments/UNLICENSE.txt %{buildroot}/usr/share/package-licenses/draco/24944bf7920108f5a4790e6071c32e9102760c37 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/draco_decoder-1.5.6
/V3/usr/bin/draco_encoder-1.5.6
/usr/bin/draco_decoder
/usr/bin/draco_decoder-1.5.6
/usr/bin/draco_encoder
/usr/bin/draco_encoder-1.5.6

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/draco/animation/keyframe_animation.h
/usr/include/draco/animation/keyframe_animation_decoder.h
/usr/include/draco/animation/keyframe_animation_encoder.h
/usr/include/draco/attributes/attribute_octahedron_transform.h
/usr/include/draco/attributes/attribute_quantization_transform.h
/usr/include/draco/attributes/attribute_transform.h
/usr/include/draco/attributes/attribute_transform_data.h
/usr/include/draco/attributes/attribute_transform_type.h
/usr/include/draco/attributes/geometry_attribute.h
/usr/include/draco/attributes/geometry_indices.h
/usr/include/draco/attributes/point_attribute.h
/usr/include/draco/compression/attributes/attributes_decoder.h
/usr/include/draco/compression/attributes/attributes_decoder_interface.h
/usr/include/draco/compression/attributes/attributes_encoder.h
/usr/include/draco/compression/attributes/kd_tree_attributes_decoder.h
/usr/include/draco/compression/attributes/kd_tree_attributes_encoder.h
/usr/include/draco/compression/attributes/kd_tree_attributes_shared.h
/usr/include/draco/compression/attributes/linear_sequencer.h
/usr/include/draco/compression/attributes/mesh_attribute_indices_encoding_data.h
/usr/include/draco/compression/attributes/normal_compression_utils.h
/usr/include/draco/compression/attributes/point_d_vector.h
/usr/include/draco/compression/attributes/points_sequencer.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_constrained_multi_parallelogram_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_constrained_multi_parallelogram_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_constrained_multi_parallelogram_shared.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_data.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_area.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_base.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_multi_parallelogram_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_multi_parallelogram_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_parallelogram_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_parallelogram_shared.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_portable_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_portable_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_tex_coords_portable_predictor.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_factory.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_interface.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_decoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_delta_decoder.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_delta_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_factory.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_interface.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_encoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_factory.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_interface.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_normal_octahedron_canonicalized_decoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_normal_octahedron_canonicalized_encoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_normal_octahedron_canonicalized_transform_base.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_normal_octahedron_decoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_normal_octahedron_encoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_normal_octahedron_transform_base.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_decoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_encoding_transform.h
/usr/include/draco/compression/attributes/prediction_schemes/prediction_scheme_wrap_transform_base.h
/usr/include/draco/compression/attributes/sequential_attribute_decoder.h
/usr/include/draco/compression/attributes/sequential_attribute_decoders_controller.h
/usr/include/draco/compression/attributes/sequential_attribute_encoder.h
/usr/include/draco/compression/attributes/sequential_attribute_encoders_controller.h
/usr/include/draco/compression/attributes/sequential_integer_attribute_decoder.h
/usr/include/draco/compression/attributes/sequential_integer_attribute_encoder.h
/usr/include/draco/compression/attributes/sequential_normal_attribute_decoder.h
/usr/include/draco/compression/attributes/sequential_normal_attribute_encoder.h
/usr/include/draco/compression/attributes/sequential_quantization_attribute_decoder.h
/usr/include/draco/compression/attributes/sequential_quantization_attribute_encoder.h
/usr/include/draco/compression/bit_coders/adaptive_rans_bit_coding_shared.h
/usr/include/draco/compression/bit_coders/adaptive_rans_bit_decoder.h
/usr/include/draco/compression/bit_coders/adaptive_rans_bit_encoder.h
/usr/include/draco/compression/bit_coders/direct_bit_decoder.h
/usr/include/draco/compression/bit_coders/direct_bit_encoder.h
/usr/include/draco/compression/bit_coders/folded_integer_bit_decoder.h
/usr/include/draco/compression/bit_coders/folded_integer_bit_encoder.h
/usr/include/draco/compression/bit_coders/rans_bit_decoder.h
/usr/include/draco/compression/bit_coders/rans_bit_encoder.h
/usr/include/draco/compression/bit_coders/symbol_bit_decoder.h
/usr/include/draco/compression/bit_coders/symbol_bit_encoder.h
/usr/include/draco/compression/config/compression_shared.h
/usr/include/draco/compression/config/decoder_options.h
/usr/include/draco/compression/config/draco_options.h
/usr/include/draco/compression/config/encoder_options.h
/usr/include/draco/compression/config/encoding_features.h
/usr/include/draco/compression/decode.h
/usr/include/draco/compression/draco_compression_options.h
/usr/include/draco/compression/encode.h
/usr/include/draco/compression/encode_base.h
/usr/include/draco/compression/entropy/ans.h
/usr/include/draco/compression/entropy/rans_symbol_coding.h
/usr/include/draco/compression/entropy/rans_symbol_decoder.h
/usr/include/draco/compression/entropy/rans_symbol_encoder.h
/usr/include/draco/compression/entropy/shannon_entropy.h
/usr/include/draco/compression/entropy/symbol_decoding.h
/usr/include/draco/compression/entropy/symbol_encoding.h
/usr/include/draco/compression/expert_encode.h
/usr/include/draco/compression/mesh/mesh_decoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_decoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_decoder_impl.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_decoder_impl_interface.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_encoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_encoder_impl.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_encoder_impl_interface.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_shared.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_traversal_decoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_traversal_encoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_traversal_predictive_decoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_traversal_predictive_encoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_traversal_valence_decoder.h
/usr/include/draco/compression/mesh/mesh_edgebreaker_traversal_valence_encoder.h
/usr/include/draco/compression/mesh/mesh_encoder.h
/usr/include/draco/compression/mesh/mesh_sequential_decoder.h
/usr/include/draco/compression/mesh/mesh_sequential_encoder.h
/usr/include/draco/compression/mesh/traverser/depth_first_traverser.h
/usr/include/draco/compression/mesh/traverser/max_prediction_degree_traverser.h
/usr/include/draco/compression/mesh/traverser/mesh_attribute_indices_encoding_observer.h
/usr/include/draco/compression/mesh/traverser/mesh_traversal_sequencer.h
/usr/include/draco/compression/mesh/traverser/traverser_base.h
/usr/include/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_decoder.h
/usr/include/draco/compression/point_cloud/algorithms/dynamic_integer_points_kd_tree_encoder.h
/usr/include/draco/compression/point_cloud/algorithms/float_points_tree_decoder.h
/usr/include/draco/compression/point_cloud/algorithms/float_points_tree_encoder.h
/usr/include/draco/compression/point_cloud/algorithms/point_cloud_compression_method.h
/usr/include/draco/compression/point_cloud/algorithms/point_cloud_types.h
/usr/include/draco/compression/point_cloud/algorithms/quantize_points_3.h
/usr/include/draco/compression/point_cloud/algorithms/queuing_policy.h
/usr/include/draco/compression/point_cloud/point_cloud_decoder.h
/usr/include/draco/compression/point_cloud/point_cloud_encoder.h
/usr/include/draco/compression/point_cloud/point_cloud_kd_tree_decoder.h
/usr/include/draco/compression/point_cloud/point_cloud_kd_tree_encoder.h
/usr/include/draco/compression/point_cloud/point_cloud_sequential_decoder.h
/usr/include/draco/compression/point_cloud/point_cloud_sequential_encoder.h
/usr/include/draco/core/bit_utils.h
/usr/include/draco/core/bounding_box.h
/usr/include/draco/core/constants.h
/usr/include/draco/core/cycle_timer.h
/usr/include/draco/core/data_buffer.h
/usr/include/draco/core/decoder_buffer.h
/usr/include/draco/core/divide.h
/usr/include/draco/core/draco_index_type.h
/usr/include/draco/core/draco_index_type_vector.h
/usr/include/draco/core/draco_types.h
/usr/include/draco/core/draco_version.h
/usr/include/draco/core/encoder_buffer.h
/usr/include/draco/core/hash_utils.h
/usr/include/draco/core/macros.h
/usr/include/draco/core/math_utils.h
/usr/include/draco/core/options.h
/usr/include/draco/core/quantization_utils.h
/usr/include/draco/core/status.h
/usr/include/draco/core/status_or.h
/usr/include/draco/core/varint_decoding.h
/usr/include/draco/core/varint_encoding.h
/usr/include/draco/core/vector_d.h
/usr/include/draco/draco_features.h
/usr/include/draco/io/file_reader_factory.h
/usr/include/draco/io/file_reader_interface.h
/usr/include/draco/io/file_utils.h
/usr/include/draco/io/file_writer_factory.h
/usr/include/draco/io/file_writer_interface.h
/usr/include/draco/io/file_writer_utils.h
/usr/include/draco/io/mesh_io.h
/usr/include/draco/io/obj_decoder.h
/usr/include/draco/io/obj_encoder.h
/usr/include/draco/io/parser_utils.h
/usr/include/draco/io/ply_decoder.h
/usr/include/draco/io/ply_encoder.h
/usr/include/draco/io/ply_property_reader.h
/usr/include/draco/io/ply_property_writer.h
/usr/include/draco/io/ply_reader.h
/usr/include/draco/io/point_cloud_io.h
/usr/include/draco/io/stdio_file_reader.h
/usr/include/draco/io/stdio_file_writer.h
/usr/include/draco/io/stl_decoder.h
/usr/include/draco/io/stl_encoder.h
/usr/include/draco/mesh/corner_table.h
/usr/include/draco/mesh/corner_table_iterators.h
/usr/include/draco/mesh/mesh.h
/usr/include/draco/mesh/mesh_are_equivalent.h
/usr/include/draco/mesh/mesh_attribute_corner_table.h
/usr/include/draco/mesh/mesh_cleanup.h
/usr/include/draco/mesh/mesh_features.h
/usr/include/draco/mesh/mesh_indices.h
/usr/include/draco/mesh/mesh_misc_functions.h
/usr/include/draco/mesh/mesh_stripifier.h
/usr/include/draco/mesh/triangle_soup_mesh_builder.h
/usr/include/draco/mesh/valence_cache.h
/usr/include/draco/metadata/geometry_metadata.h
/usr/include/draco/metadata/metadata.h
/usr/include/draco/metadata/metadata_decoder.h
/usr/include/draco/metadata/metadata_encoder.h
/usr/include/draco/metadata/property_table.h
/usr/include/draco/metadata/structural_metadata.h
/usr/include/draco/point_cloud/point_cloud.h
/usr/include/draco/point_cloud/point_cloud_builder.h
/usr/lib64/libdraco.so
/usr/lib64/pkgconfig/draco.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libdraco.so.8.0.0
/usr/lib64/libdraco.so.8
/usr/lib64/libdraco.so.8.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/draco/24944bf7920108f5a4790e6071c32e9102760c37
/usr/share/package-licenses/draco/623115fff0087fad82d8c7a34b67dc8de932cf61
